receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      process:
        include: 
          names: ['otelsmol']
          match_type: strict

  prometheus/node_exporter:
    config:
      scrape_configs:
        - job_name: 'node_exporter'
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:9100']

  prometheus/my_real_app:
    config:
      scrape_configs:
        - job_name: 'my_real_app'
          scrape_interval: 5m
          static_configs:
            - targets: ['localhost:9001']
          metric_relabel_configs:
            - source_labels: [series_id]
              regex: '^0|^1'
              action: keep

  prometheus/otel_collector:
    config:
      scrape_configs:
        - job_name: 'otel_collector'
          scrape_interval: 1m
          static_configs:
            - targets: ['localhost:8888']

processors:
  batch:
    send_batch_size: 10000
    timeout: 15s

exporters:
  otlphttp:
    endpoint: 'http://localhost:42069'
  file:
    path: 'metrics.json'

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    metrics/prometheus:
      receivers: [prometheus/node_exporter, prometheus/my_real_app, prometheus/otel_collector]
      processors: [batch]
      exporters: [otlphttp]
    metrics/process:
      receivers: [hostmetrics]
      exporters: [file]
    
